# ~/.config/starship.toml

add_newline = true
#command_timeout = 1000
#format = """$os$username$localip$hostname$memory_usage$kubernetes$directory$shell$git_branch\n$character"""

#format = """\
#[â•­â•¼ ](250)$os\
#$username$hostname$memory_usage$kubernetes$directory$shell$git_branch\
#\n[â•°â”€â•¼](250)$character\
#"""
#\n[â”‚](250)\
#\n[â””â”€](250)$character\

format = """
[â•­â•¼](fg:002) $os \
$username$hostname$memory_usage\
$directory$time\
\n[](190)$character \
"""

# change the default prompt characters
[character]
error_symbol = '[â•°â”€ï…¸](001)'
success_symbol = '[â•°â”€ï…¸](002)'

# ---

[os]
#format = "on [($name )]($style)"
format = '[$symbol](012) '
#style = "bold blue"
disabled = false

[os.symbols]
#Windows = "î˜ª "
#Arch = "Arch is the best! "
Android = "ï…» "
#Kali = "ï…» "
Arch = "ïŒƒ "
#Kali = "ïŒƒ "
Artix = "ïŒŸ "
#Kali = "ïŒŸ "
Debian = "ïŒ† "
#Kali = "ïŒ† "
DragonFly = "îŠ "
#Kali = "îŠ "
Emscripten = "ïˆ… "
#Kali = "ïˆ… "
Fedora = "ïŒŠ "
#Kali = "ïŒŠ "
Garuda = "ó°›“ "
#Kali = "ó°›“ "
Illumos = "ó°ˆ¸ "
#Kali = "ó°ˆ¸"
Kali = "ïŒ§"
Linux = "ïŒš "
#Kali = "ïŒš "
Macos = "ïŒ‚ "
#Kali = "ïŒ‚ "
NixOS = "ïŒ“ "
#Kali = "ïŒ“ "
OracleLinux = "ó°Œ· "
#Kali = "ó°Œ· "
Raspbian = "ïŒ• "
#Kali = "ïŒ• "
Solus = "ó° ³ "
#Kali = "ó° ³ "
Ubuntu = "ïŒ› "
#Kali = "ïŒ› "
Windows = "ó°² "
#Kali = "ó°² "
# ---

# Shows the username
[username]
format = '[on](fg:#A4B1CD) [${user}${ssh_symbol}](012) '
style_root = 'black bold'
style_user = 'white bold'
#format = ' [$user](250) '
disabled = false
show_always = true

# Shows the IP Addr
[localip]
disabled = false
format = '[@$localipv4](009) '
ssh_only = false

# Shows the hostname
[hostname]
disabled = false
format = 'on [${hostname}${ssh_symbol}](006) '
ssh_only = true
ssh_symbol = "î¬ "

# Shows the memory usage
[memory_usage]
disabled = false
format = '[$symbol ${ram_pct}](001) '
style = 'bold dimmed green'
symbol = "ó°›"
threshold = 15

# Shows current directory
[directory]
format = '[at](fg:#A4B1CD) [$path](002)[$read_only](013) '
home_symbol = 'ó°‹œ ~'
read_only = " ó°Œ¾ "
read_only_style = '013'
truncation_length = 5
truncation_symbol = 'â€¦/'
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[time]
disabled = false
#style='bg:#1d2230'
format = '[[ ï€— $time ](fg:#A4B1CD)]($style) '
time_format = '%r'
#time_range = '10:00:00-14:00:00'
#utc_time_offset = '-5'

[status]
disabled = false
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
not_executable_symbol = 'âœ— NOT EXECUTABLE '
not_found_symbol = 'âœ—'
sigint_symbol = 'âœ—'
signal_symbol = 'âœ—'
success_symbol = 'âœ” SUCCESS'
symbol = 'âœ— FAILED '

#show the shell

#show the Battery
#ï‰„
#ï‰
#ï‰€
#ï‰ƒ

# Shows current git branch
#[git_branch]
#symbol = 'ï‡’ '
#format = 'via [$symbol$branch]($style)'
#truncation_length = 1
#truncation_symbol = 'â€¦/'
#style = 'bold green'
[git_branch]
format = '[ $symbol $branch ]($style)'
style = ""
symbol = "ï˜"

# Shows current git status
#[git_status]
#format = '[$all_status$ahead_behind]($style) '
#style = 'bold green'
#conflicted = 'ğŸ³'
#up_to_date = ''
#untracked = ' ï”© '
#ahead = 'â‡¡${count}'
#diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
#behind = 'â‡£${count}'
#stashed = ' ó±— '
#modified = ' ï„ '
#staged = ' [++\($count\)](green)'
#renamed = ' è¥ '
#deleted = ' ï€” '

# Shows kubernetes context and namespace
[kubernetes]
disabled = true
format = 'via [ó±ƒ¾ $context\($namespace\)](bold purple) '

[docker_context]
disabled = true
symbol = "ïŒˆ "

[python]
disabled = true
symbol = "îˆµ "

[php]
symbol = "î˜ˆ "

# ---

[vagrant]
disabled = true

[helm]
disabled = true

[nodejs]
disabled = true
symbol = "îœ˜ "

[ruby]
disabled = true
symbol = "î‘ "

[terraform]
disabled = true

[package]
symbol = "ó°— "

[perl]
symbol = "î™¾ "

[pijul_channel]
symbol = "ï˜ "

[rlang]
symbol = "ó°Ÿ” "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[swift]
symbol = "î• "

[zig]
symbol = "îš© "

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[crystal]
symbol = "î˜¯ "

[dart]
symbol = "î˜ "

[elixir]
symbol = "î˜­ "

[elm]
symbol = "î˜¬ "

[fennel]
symbol = "îš¯ "

[fossil_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[guix_shell]
symbol = "ïŒ¥ "

[haskell]
symbol = "î· "

[haxe]
symbol = "î™¦ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[kotlin]
symbol = "î˜´ "

[lua]
symbol = "î˜  "

[meson]
symbol = "ó°”· "

[nim]
symbol = "ó°†¥ "

[nix_shell]
symbol = "ïŒ“ "

[ocaml]
symbol = "î™º "

#----------------------------------------------

#add_newline = false
#command_timeout = 1000
#format = """$os$username$hostname$kubernetes$directory$git_branch$git_status"""

# Drop ugly default prompt characters
#[character]
#success_symbol = ''
#error_symbol = ''

# ---

#[os]
#format = '[$symbol](bold white) '   
#disabled = false

#[os.symbols]
#Linux = 'ï…¼'
#Windows = 'î˜ª'
#Arch = 'ó°£‡'
#Ubuntu = 'ïŒ›'
#Macos = 'ó°€µ'

# ---

# Shows the username
#[username]
#style_user = 'white bold'
#style_root = 'black bold'
#format = '[$user]($style) '
#disabled = false
#show_always = true

# Shows the hostname
#[hostname]
#ssh_only = false
#format = 'on [$hostname](bold yellow) '
#disabled = false

# Shows current directory
#[directory]
#truncation_length = 1
#truncation_symbol = 'â€¦/'
#home_symbol = 'ó°‹œ ~'
#read_only_style = '197'
#read_only = ' ï€£ '
#format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
#[git_branch]
#symbol = 'ï‡’ '
#format = 'via [$symbol$branch]($style)'
# truncation_length = 4
#truncation_symbol = 'â€¦/'
#style = 'bold green'

# Shows current git status
#[git_status]
#format = '[$all_status$ahead_behind]($style) '
#style = 'bold green'
#conflicted = 'ğŸ³'
#up_to_date = ''
#untracked = 'ï”© '
#ahead = 'â‡¡${count}'
#diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
#behind = 'â‡£${count}'
#stashed = 'ï£– '
#modified = 'ï„ '
#staged = '[++\($count\)](green)'
#renamed = 'è¥ '
#deleted = 'ï€” '

# Shows kubernetes context and namespace
#[kubernetes]
#format = 'via [ó±ƒ¾ $context\($namespace\)](bold purple) '
#disabled = false

# ---

#[vagrant]
#disabled = true

#[docker_context]
#disabled = true

#[helm]
#disabled = true

#[python]
#disabled = true

#[nodejs]
#disabled = true

#[ruby]
#disabled = true

#[terraform]
#disabled = true
