# ~/.config/starship.toml

add_newline = true
#command_timeout = 1000
#format = """$os$username$localip$hostname$memory_usage$kubernetes$directory$shell$git_branch\n$character"""

format = """\
[â•­â•¼ ](250)$os\
$username$localip$hostname$memory_usage$kubernetes$directory$shell$git_branch\
\n[â•°â•¼](250)$character\
"""

# chaneg the default prompt characters
[character]
success_symbol = '[ï…¸](250)'
error_symbol = '[ï…¸](250)'

# ---

[os]
#format = "on [($name )]($style)"
format = '[$symbol](250) '   
#style = "bold blue"
disabled = false

[os.symbols]
#Windows = "î˜ª "
#Arch = "Arch is the best! "
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§"
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
# ---

# Shows the username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = ' [$user](250) '
disabled = false
show_always = true

# Shows the IP Addr
[localip]
ssh_only = false
format = '[@$localipv4](003) '
disabled = false

# Shows the hostname
[hostname]
ssh_only = false
format = 'on [${hostname}${ssh_symbol}](004) '
disabled = false
ssh_symbol = "î¬ "

# Shows the memory usage
[memory_usage]
format ='[$symbol ${ram_pct}](001) '
disabled = false
threshold = 50
#symbol = 'ó°’‹'
style = 'bold dimmed green'
symbol = "ó°›"
# Shows current directory
[directory]
truncation_length = 5
truncation_symbol = 'â€¦/'
home_symbol = 'ó°‹œ ~'
read_only_style = '197'
read_only = " ó°Œ¾ "
format = 'at [$path](190)[$read_only](003) '
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

#show the shell

#show the Battery
#ï‰„
#ï‰
#ï‰€
#ï‰ƒ










# Shows current git branch
#[git_branch]
#symbol = 'ï‡’ '
#format = 'via [$symbol$branch]($style)'
#truncation_length = 1
#truncation_symbol = 'â€¦/'
#style = 'bold green'
[git_branch]
symbol = "ï˜"
style = ""
format = '[ $symbol $branch ]($style)'



# Shows current git status
#[git_status]
#format = '[$all_status$ahead_behind]($style) '
#style = 'bold green'
#conflicted = 'ğŸ³'
#up_to_date = ''
#untracked = ' ï”© '
#ahead = 'â‡¡${count}'
#diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
#behind = 'â‡£${count}'
#stashed = ' ó±— '
#modified = ' ï„ '
#staged = ' [++\($count\)](green)'
#renamed = ' è¥ '
#deleted = ' ï€” '


# Shows kubernetes context and namespace
[kubernetes]
format = 'via [ó±ƒ¾ $context\($namespace\)](bold purple) '
disabled = true

[docker_context]
disabled = true
symbol = "ïŒˆ "

[python]
disabled = true
symbol = "îˆµ "

[php]
symbol = "î˜ˆ "




# ---

[vagrant]
disabled = true



[helm]
disabled = true


[nodejs]
disabled = true
symbol = "îœ˜ "

[ruby]
disabled = true
symbol = "î‘ "

[terraform]
disabled = true

[package]
symbol = "ó°— "

[perl]
symbol = "î™¾ "



[pijul_channel]
symbol = "ï˜ "

[rlang]
symbol = "ó°Ÿ” "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[swift]
symbol = "î• "

[zig]
symbol = "îš© "

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[crystal]
symbol = "î˜¯ "

[dart]
symbol = "î˜ "

[elixir]
symbol = "î˜­ "

[elm]
symbol = "î˜¬ "

[fennel]
symbol = "îš¯ "

[fossil_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[guix_shell]
symbol = "ïŒ¥ "

[haskell]
symbol = "î· "

[haxe]
symbol = "î™¦ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[kotlin]
symbol = "î˜´ "

[lua]
symbol = "î˜  "

[meson]
symbol = "ó°”· "

[nim]
symbol = "ó°†¥ "

[nix_shell]
symbol = "ïŒ“ "

[ocaml]
symbol = "î™º "















#----------------------------------------------





#add_newline = false
#command_timeout = 1000
#format = """$os$username$hostname$kubernetes$directory$git_branch$git_status"""

# Drop ugly default prompt characters
#[character]
#success_symbol = ''
#error_symbol = ''

# ---

#[os]
#format = '[$symbol](bold white) '   
#disabled = false

#[os.symbols]
#Linux = 'ï…¼'
#Windows = 'î˜ª'
#Arch = 'ó°£‡'
#Ubuntu = 'ïŒ›'
#Macos = 'ó°€µ'

# ---

# Shows the username
#[username]
#style_user = 'white bold'
#style_root = 'black bold'
#format = '[$user]($style) '
#disabled = false
#show_always = true

# Shows the hostname
#[hostname]
#ssh_only = false
#format = 'on [$hostname](bold yellow) '
#disabled = false

# Shows current directory
#[directory]
#truncation_length = 1
#truncation_symbol = 'â€¦/'
#home_symbol = 'ó°‹œ ~'
#read_only_style = '197'
#read_only = ' ï€£ '
#format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
#[git_branch]
#symbol = 'ï‡’ '
#format = 'via [$symbol$branch]($style)'
# truncation_length = 4
#truncation_symbol = 'â€¦/'
#style = 'bold green'

# Shows current git status
#[git_status]
#format = '[$all_status$ahead_behind]($style) '
#style = 'bold green'
#conflicted = 'ğŸ³'
#up_to_date = ''
#untracked = 'ï”© '
#ahead = 'â‡¡${count}'
#diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
#behind = 'â‡£${count}'
#stashed = 'ï£– '
#modified = 'ï„ '
#staged = '[++\($count\)](green)'
#renamed = 'è¥ '
#deleted = 'ï€” '

# Shows kubernetes context and namespace
#[kubernetes]
#format = 'via [ó±ƒ¾ $context\($namespace\)](bold purple) '
#disabled = false

# ---

#[vagrant]
#disabled = true

#[docker_context]
#disabled = true

#[helm]
#disabled = true

#[python]
#disabled = true

#[nodejs]
#disabled = true

#[ruby]
#disabled = true

#[terraform]
#disabled = true




















